# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run tests
        run: dart test
        env:
          TEST_VALUE: 1
          TEST_BOOL: true
          TEST_DB_ENV_VAR: 'postgres://user:password@host:5432/dbname'

      - name: Run tests with compiled runtime
        run: dart tool/runtime_test_runner.dart
